export const roles = "api/role"
export const portUrl='api/port'
export const currencyUrl='api/currency'
export const addressUrl = 'api/address'
export const customerUrl = 'api/customer'
export const mblUrl = 'api/mbl'
export const mblbyID ='api/mblbyid'
export const hblUrl = "api/hbl"
export const shipmentBytype = "api/shipmentbytype"
export const mblbyShipmentid = "api/mblbyshipment";
export const hblbyShipmentUrl ="api/hblbyshipment"
